### ISSUE TITLE
Silently fails if some training or validate examples are too large

### ISSUE THREAD

**Issue by aplakhov** [tune-the-model/tune-the-model-py#3]
In my experiments 32000 characters are too large while 2000 is ok.
An API probably should fail immediately at least warn user if too large strings are used in samples.

**Comment by drewxa** [comment]
Thanks for the bug report.

We have improved our learning process, now there is no limit on the length of the input data and on the length of the target.
So you don't have to worry about it.
And I'm closing this issue.
